[#macro renderULForNavigation navigation renderAnyway ulType navType]
	[#assign UL_FOR_RENDERING = ""]
	[#assign hasRenderedUL = false]

	[#list navigation.items as item]
		[#-------------------------]
		[#-- VERTICAL NAVIGATION --]
		[#-------------------------]
		[#if navType == "vertical"]
			[#if (item.open || item.selected || renderAnyway) && item.level > 1]
				[#if ! hasRenderedUL]

					[#if ulType == "startUL"]
						[#assign UL_FOR_RENDERING = "<ul class=\"level-${item.level}\">" ]
					[#else]
						[#assign UL_FOR_RENDERING = "</ul>" ]
					[/#if]

					${UL_FOR_RENDERING}
	
					[#assign hasRenderedUL = true]
				[/#if]
			[/#if]
		[#---------------------------]
		[#-- HORIZONTAL NAVIGATION --]
		[#---------------------------]
		[#else]
			[#assign itemContent = item.getContent()!]
			[#assign showFlyout = itemContent.showFlyoutMenu!false]
			[#assign numberOfChildren = item.getItems()?size]
			[#assign cssWideClass = "wide"]
			[#assign setWideClass = false]

			[#if showFlyout || item.level == 1]
				[#if ! hasRenderedUL]
					[#-------------------------------------------]
					[#-- HANDLE WIDE CLASS FOR SECOND LEVEL UL --]
					[#-------------------------------------------]
					[#if item.level == 2]
						[#list item.items as childItem]
							[#assign childItemContent = childItem.getContent()!]
							[#assign showFlyoutOnChild = childItemContent.showFlyoutMenu!false]

							[#if showFlyoutOnChild]
								[#assign setWideClass = true]
							[/#if]
						[/#list]
					[/#if]

					[#if ulType == "startUL"]
						[#if setWideClass]
							[#assign UL_FOR_RENDERING = "<ul class=\"level-${item.level} ${cssWideClass!}\">" ]
						[#else]
							[#assign UL_FOR_RENDERING = "<ul class=\"level-${item.level}\">" ]
						[/#if]
					[#else]
						[#assign UL_FOR_RENDERING = "</ul>" ]
					[/#if]

					${UL_FOR_RENDERING}

					[#assign hasRenderedUL = true]
				[/#if]
			[/#if]
		[/#if]
	[/#list]
[/#macro]